### ISSUE TITLE
Getting error while clickin on the login link .

### ISSUE THREAD

**Issue by memayank2007** [wingrunr21/omniauth-amazon#6]
Getting following error:
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

**Comment by faizanayyub** [comment]
I'm also getting the same error on Amazon. Any solution for this?

**Comment by jamesa** [comment]
This can happen if you are not sending your Amazon Client ID and Amazon Client Secret correctly. Verify that when setting up the provider (see Usage in the README) that the Client ID and Secret are correct.
