### ISSUE TITLE
Fix for missing required parameter : code

### ISSUE THREAD

**Issue by russau** [wingrunr21/omniauth-amazon#7]
I recently integrated this gem and was stuck for a while with an error: 

```
invalid_request: The request is missing a required parameter : code {"error":"invalid_request","error_description":"The request is missing a required parameter : code"}
```
Just figured out my mistake.  I followed the "login with amazon" instructions at https://login.amazon.com/website.  Which takes you through an *Implicit Grant* to obtain a token.  omni-auth is expecting an Authorization Code Grant.  Easily fixed, ensure you pass configure the correct repsonse type option.

``` javascript
    options = { scope : 'profile', response_type : 'code' };
```

More information on the different workflows in the [developer guide](https://images-na.ssl-images-amazon.com/images/G/01/lwa/dev/docs/website-developer-guide._TTH_.pdf).

**Comment by wingrunr21** [comment]
Hmm, interesting. Thanks for the update. I'll push a fix for that this weekend.

**Comment by russau** [comment]
Is there a need for a fix?  Or just a mention on the README.md?

**Comment by russau** [comment]
I forget to mention that the initializer needs `provider_ignores_state` when I integrate this way

```ruby
  provider :amazon, ENV['AMAZON_CLIENT_ID'], ENV['AMAZON_CLIENT_SECRET'], {:provider_ignores_state => true}
```

Login with Amazon is able to pass the state parameter along, but I'm not sure how to integrate this with omniauth.

**Comment by wingrunr21** [comment]
Well, as the `response_type` is actually a required OAuth2 parameter (and also required for this to work), I figure might as well set it up in the gem and not require people to configure it. It can always be overridden if possible later. Same probably goes to `provider_ignores_state`.

**Comment by russau** [comment]
response_type I typed into my view myself.  Is there a way omni-auth can do this for me?

**Comment by philipgiuliani** [comment]
I have the same problem and have included the latest version.

My callback url looks like this:
```
http://localhost:3000/auth/amazon/callback?access_token=Atza%7CIQEBLjAsAhRX...3EH2dwLCXrs&token_type=bearer&expires_in=3138&scope=profile
```

Error:
```
invalid_request: The request is missing a required parameter : code {"error_description":"The request is missing a required parameter : code","error":"invalid_request"}
```
